application:
  name: unipocket

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

jwt:
  secret: ${JWT_SECRET:your-secret-key-must-be-at-least-32-characters-long-for-hs256}
  access-token-expiration: 1800000 # 30분 (밀리초)
  refresh-token-expiration: 864000000 # 10일 (밀리초)
