name: Backend CD

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'backend/**'
  # 테스트를 위한 수동 실행 가능
  workflow_dispatch:

defaults:
  run:
    working-directory: ./backend

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      # CI에서 이미 검증되었다고 가정 -x test로 스킵하여 배포 속도를 높임
      - name: Build with Gradle
        run: ./gradlew clean build -x test

#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ap-northeast-2
#
#      # 빌드된 jar를 S3에 백업 (롤백을 위해 백업함)
#      - name: Upload to S3
#        run: aws s3 cp ./build/libs/app.jar s3://${{ secrets.S3_BUCKET_NAME }}/deploy/app.jar

      # jar를 EC2로 전송 및 배포 스크립트 실행
      - name: Deploy to EC2
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          echo "${{ secrets.EC2_SSH_KEY }}" | ssh-add -
          ssh-keyscan -H -p ${{ secrets.EC2_PORT }} ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
           
          echo "export LOG_PATH='${{ secrets.LOG_PATH }}'" >> env.sh
          echo "export DB_URL='${{ secrets.DB_URL }}'" > env.sh
          echo "export DB_USER='${{ secrets.DB_USER }}'" >> env.sh
          echo "export DB_PASSWORD='${{ secrets.DB_PASSWORD }}'" >> env.sh
          
          scp -P ${{ secrets.EC2_PORT }} ./env.sh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ec2-user/app/env.sh
          scp -P ${{ secrets.EC2_PORT }} ./build/libs/app.jar ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ec2-user/app/app.jar
          ssh -p ${{ secrets.EC2_PORT }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "chmod +x /home/ec2-user/app/deploy.sh && /home/ec2-user/app/deploy.sh"
